### ISSUE TITLE
Add initial unit tests

### ISSUE THREAD

**Issue by yspolyakov** [openfheorg/openfhe-python#53]

**Comment by sei-adolgert** [comment]
Hi Rener and Yuriy. Could I help with this? What I see for a first task is: Rename the "test" directory to "tests" so it agrees with Python's usual name. Make a pytest that is a "smoke test" so it just imports the library. Then setup pytest to take a command-line argument so that the default is a short set of tests (to run on Github) and a flag for longer set of tests (because there's no way Github will run FHE workloads that are more than very short). Does that sound like a start?

**Comment by reneroliveira** [comment]
> Hi Rener and Yuriy. Could I help with this? What I see for a first task is: Rename the "test" directory to "tests" so it agrees with Python's usual name. Make a pytest that is a "smoke test" so it just imports the library. Then setup pytest to take a command-line argument so that the default is a short set of tests (to run on Github) and a flag for longer set of tests (because there's no way Github will run FHE workloads that are more than very short). Does that sound like a start?

@sei-adolgert sounds like a good idea, for sure!

**Comment by sei-adolgert** [comment]
Rener, thanks for the message. I made a PR with a first commit. It's a way to say, yes, this is on the right track, for something small. Or, no, not the right track. Are you able to review a PR? https://github.com/openfheorg/openfhe-python/pull/103

**Comment by yspolyakov** [comment]
@sei-adolgert  Could you create another PR adding some documentation about running the tests to the main README.md file and then pointing to tests/README.md for more details.
